FamilyDiary/Models/DiaryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FamilyDiary.Models
{
    public class DiaryViewModel
    {
        public QuestionViewModel Question { get; set; }
        public IList<QuestionViewModel> LatestQuestions { get; set; }

        public string UserName { get; set; }

        public IList<Answer> Answers { get; set; }
    }
}

FamilyDiary/Controllers/DiaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FamilyDiary.Models;
using System.Web.Routing;
using Microsoft.Web.Mvc;
using System.Text.RegularExpressions;
using FamilyDiary.Models.Account;
using Ninject;
using System.Net.Mail;
using System.Text;
using FamilyDiary.RequestModels;

namespace FamilyDiary.Controllers
{
    public class DiaryController : Controller
    {
        [Inject]
        public IRepository Repository { get; set; }

        [Inject]
        public IFormsAuthenticationService FormsService { get; set; }
        
        [Inject]
        public IHtmlSanitizer HtmlSanitizer { get; set; }

        [Inject]
        public IEmailService EmailService { get; set; }

        [Inject]
        public IMembershipService MembershipService { get; set; }

        [Inject]
        public IFileSystem FileSystem { get; set; }

        public int LatestQuestionsMaxSize { get; set; }

        public DiaryController()
        {
            this.LatestQuestionsMaxSize = 10;
        }

        [Authorize]
        [HttpGet]
        public ActionResult Main(int? questionId = null)
        {

            var model = new DiaryViewModel();
            model.UserName = FormsService.GetLoggedInUserName();

            // prepare the latest questions list
            var userAnswers = from a in Repository.GetAllAnswers()
                              where a.UserName == model.UserName
                              select new { QuestionId = a.QuestionId };


            var latestQuestions = (from q in Repository.GetAllQuestions()
                                   orderby q.Id descending
                                   select new QuestionViewModel(q)
                                   {
                                       IsAnswered = userAnswers.Any(a => a.QuestionId == q.Id)
                                   }).Take(LatestQuestionsMaxSize);

            model.LatestQuestions = latestQuestions.ToList();

            // prepare the active question
            if (!questionId.HasValue)
            {
                model.Question = model.LatestQuestions.First();
            }
            else
            {
                model.Question = model.LatestQuestions.FirstOrDefault(q => q.Id == questionId.Value);

                if (model.Question == null)
                {
                    var question = Repository.GetAllQuestions().First(q => q.Id == questionId.Value);
                    model.Question = new QuestionViewModel(question)
                    {
                        IsAnswered = userAnswers.Any(a => a.QuestionId == question.Id)
                    };
                }
            }

            model.Question.IsActive = true;
            model.Answers = (from a in Repository.GetAllAnswers()
                          where a.QuestionId == model.Question.Id
                          orderby a.Id descending
                          select a).ToList();

            return View(model);
        }

        [Authorize]
        [HttpPost]
        public ActionResult AddQuestion([Bind(Prefix="")] QuestionRequestModel model)
        {
            model.Id = 0;
            var question = new Question();
            ModelCopier.CopyModel(model, question);
            question.Date = DateTime.Now;
        
            int questionId = Repository.InsertQuestion(question);

            if (model.SendMail)
            {
                var username = FormsService.GetLoggedInUserName();

                var emailBody = FileSystem.FileReadAllText(this.Server.MapPath("~/Views/Emails/NewQuestionEmail.htm"));
                emailBody = emailBody.Replace("{QUESTION}", model.Long)
                    .Replace("{USERNAME}", username)
                    .Replace("{QUESTIONID}", questionId.ToString());

                SendEmail(
                    subject: String.Format("Nueva pregunta de {0}!", username),
                    body: emailBody);
            }
            return RedirectToAction("Main");
        }

        [Authorize]
        [HttpPost]
        public ActionResult AddAnswer(AnswerRequestModel model)
        {
            model.Text = HtmlSanitizer.Sanitize(model.Text);
            model.Id = 0;

            var answer =  new Answer();
            ModelCopier.CopyModel(model, answer);
            answer.Date = DateTime.Now;
            answer.UserName = FormsService.GetLoggedInUserName();

            Repository.InsertAnswer(answer);

            if (model.SendMail)
            {
                string question = Repository.GetAllQuestions().Where(q => q.Id == model.QuestionId).FirstOrDefault().Long;

                var emailBody = FileSystem.FileReadAllText(this.Server.MapPath("~/Views/Emails/NewAnswerEmail.htm"));
                emailBody = emailBody.Replace("{QUESTION}", question)
                    .Replace("{USERNAME}", answer.UserName)
                    .Replace("{ANSWER}", answer.Text)
                    .Replace("{QUESTIONID}", answer.QuestionId.ToString());

                SendEmail(
                    subject: String.Format("Nueva respuesta de {0}!", answer.UserName),
                    body: emailBody);
            }
            return Json(model.Text);
        }

        private void SendEmail(string subject, string body)
        {
            var message = new MailMessage(
                from: "fede@farmas.net",
                to: String.Join(",", MembershipService.GetAllUserEmailAddress()),
                subject: subject,
                body: body);

            message.IsBodyHtml = true;
            message.ReplyToList.Add(new MailAddress("fsilva.armas@gmail.com"));

            EmailService.Send(message);
        }
    }
}

FamilyDiary/Views/Diary/AnswerPartialView.cshtml
@model FamilyDiary.Models.Answer

@{
    Layout = null;
}

<div class="answer rounded-corners">
	<div class="user rounded-corners">
		<img class="rounded-corners" src='@Href(String.Format("~/content/images/users/{0}.png", Model.UserName))' />
		<div class="rounded-corners">
			<span class="user-name">@Model.UserName</span> dijo:
			<span class="user-date">@Model.Date.ToShortDateString()</span>
		</div>	
	</div>			 
	<div class="answer-text">
        @Html.Raw(Model.Text)
	</div>
</div>

FamilyDiary/Views/Diary/Main.cshtml
@model FamilyDiary.Models.DiaryViewModel

@section head {
    <link href='@Href("~/content/wysiwyg/jquery.wysiwyg.css")' rel="stylesheet" type="text/css" />
    <link href='@Href("~/content/css/main.css")' rel="stylesheet" type="text/css" />
    <script src='@Href("~/content/wysiwyg/jquery.wysiwyg.js")' type="text/javascript"></script>	
    <script src='@Href("~/content/wysiwyg/wysiwyg.image.js")' type="text/javascript"></script>	
    <script src='@Href("~/content/wysiwyg/wysiwyg.link.js")' type="text/javascript"></script>	
    <script src='@Href("~/content/scripts/main.js")' type="text/javascript"></script>    

}

    <div id="header">
        <div class="header-user">
            <img class="rounded-corners" src='@Href(String.Format("~/content/images/users/{0}.png", Model.UserName))' />
            
        </div>
        <div class="question rounded-corners">
            <div class="question-date rounded-corners">
              <span class="day">@Model.Question.Date.Day</span> 
              <span class="month">@Model.Question.Date.ToString("MMMM", new System.Globalization.CultureInfo("es")).Remove(3)</span> 
              <span class="year">@Model.Question.Date.Year</span>
            </div>
            <div class="question-text">
                @Model.Question.Long
            </div>
        </div>
    </div>
    <br />
    <div id="left">   
        <div id="answerDiv" class="answer rounded-corners">
            <span id="message">Procesando...</span>
            <div class="user rounded-corners">
                <img class="rounded-corners" src='@Href(String.Format("~/content/images/users/{0}.png", Model.UserName))' />
                <div class="rounded-corners">
                    <span class="user-name">@Model.UserName</span> dice:			
                </div>	
            </div>		         	 
            <div class="answer-text">
                <input type="hidden" id="username" name="username" value="@Model.UserName" />
                <input type="hidden" id="url" name="url" value='@Url.Action("AddAnswer")' />
                <input type="hidden" id="questionid" name="questionid" value="@Model.Question.Id" />
                <textarea id="answerText" name="Text" rows="10" cols="80"></textarea> 
                <input type="button" id="answerButton" class="answer-button" value="Responde" />	
                <input type="checkbox" id="answerSendMailCheckbox" checked="checked" value="true" />
                <label for="answerSendMailCheckbox">Mandar Correo</label>
            </div>
        </div>
        
        <div id="newAnswerDiv" class="answer rounded-corners">
            <div class="user rounded-corners">
                <img class="rounded-corners" src='@Href(String.Format("~/content/images/users/{0}.png", Model.UserName))' />
                <div class="rounded-corners">
                    <span class="user-name">@Model.UserName</span> dijo:
                    <span class="user-date">Ahorita</span>
                </div>	
            </div>			 
            <div class="answer-text">
            </div>
        </div>
        
        @foreach (var answer in Model.Answers)
        {
            Html.RenderPartial("AnswerPartialView", answer);
        }
        
    </div>
    <div id="right">
        <div id="logoutDiv" class="menu-action rounded-corners clickable">
            <input type="hidden" value='@Url.Action("LogOff", "Account")' />
            Salir
        </div>
        
        <div id="newQuestionDiv" class="menu-action rounded-corners">
            Nueva Entrada		
        </div>
        <div id="newQuestionDialog" class="new-question-dialog" title="Escribele a la familia">	
            @using (Html.BeginForm("AddQuestion", "Diary", FormMethod.Post, new { id = "newQuestionForm" }))
            {			
                <fieldset class="rounded-corners">
                    <label class="entrada" for="short">Titulo Corto:</label>
                    <input type="text" id="short" name="short" class="required" />
                    <label class="entrada" for="long">Titulo:</label>
                    <textarea id="long" name="long" rows="3" cols="50" class="required"></textarea>
                    <br />
                    <input type="checkbox" id="questionSendMailCheckbox" name="sendMail" checked="checked" value="true" />
                    <label for="questionSendMailCheckbox">Mandar Correo</label>
                </fieldset>
            }
        </div>
        
        <br />
        @foreach (var q in Model.LatestQuestions)
        {
        <div class="old-question rounded-corners clickable @if (q.IsActive)
                                                     { <text>active-question</text>}">
            
            <input type="hidden" value='@Url.Action("Main", new { questionId = q.Id })' />
            @if (!q.IsAnswered)
            {
            <img src='@Href("~/content/images/new-text.png")' />
            }
            @q.Short       
        </div>
        }
    </div>